name= "react-portfolio-website"
compatibility_date = "2025-03-06"
type = "javascript"

[build]
command = "npm run build"  # or your build command
cwd = "."  # Current working directory

[env.production]
pages_build_output_dir = "./dist"  # Point to your build output folder
